codecov:
  require_ci_to_pass: yes
  token: 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

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        flags: unittests
